### PR TITLE
Add link to previous discussion of Explicit Resource Management

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by ljharb** [comment]
Can you make this PR to the main notes repo? This is just a fork.

**Comment by chicoxyzzy** [comment]
I forget about it every time :)

**Comment by hax** [comment]
@ljharb I'm curious why not transfer rwaldron/tc39-notes to tc39 org so we will not "forget" it anymore. And it's more clear for community contributors (like fix typo).

**Comment by ljharb** [comment]
You’d have to ask rwaldron that.

**Pull request closed without merging**
